# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":cdck"
    replace: "Civilized Discourse Construction Kit"

  # Dates
  - trigger: ":today"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: shell
        params:
          cmd: ~/.local/bin/today

  - trigger: ":tomorrow"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: shell
        params:
          cmd: ~/.local/bin/tomorrow

  - trigger: ":monday"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: shell
        params:
          cmd: ~/.local/bin/nextmonday

  # Symbols
  - {trigger: ":section", replace: "§"}
  - {trigger: ":paragraph", replace: "¶"}
  - {trigger: ":pilcrow", replace: "¶"}
  - {trigger: ":-m", replace: "—"}
  - {trigger: ":-n", replace: "–"}
  - {trigger: ":...", replace: "…"}

  # Shell commands
  #- trigger: ":shell"
  #  replace: "{{output}}"
  #  vars:
  #    - name: output
  #      type: shell
  #      params:
  #        cmd: "echo Hello from your shell"
