# https://espanso.org/docs/

matches:
  # Simple Expansions
  - {trigger: ";cdck",   replace: "Civilized Discourse Construction Kit"}
  - {trigger: ";kem",    replace: "Kyle E. Mitchell"}
  - {trigger: ";email",  replace: "kyle@kemitchell.com"}
  - {trigger: ";pfnc",   replace: "PolyForm Noncommercial"}
  - {trigger: ";pfft",   replace: "PolyForm Free Trial"}
  - {trigger: ";gpl",    replace: "General Public License"}
  - {trigger: ";kemred", replace: "Redline (KEM generated)"}

  # Dates
  - trigger: ";today"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: shell
        params:
          cmd: ~/.local/bin/today

  - trigger: ";tomorrow"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: shell
        params:
          cmd: ~/.local/bin/tomorrow

  - trigger: ";yesterday"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: shell
        params:
          cmd: ~/.local/bin/yesterday

  - trigger: ";monday"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: shell
        params:
          cmd: ~/.local/bin/nextmonday

  - trigger: ";friday"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: shell
        params:
          cmd: ~/.local/bin/friday

  # Symbols
  - {trigger: ";section",   replace: "§"}
  - {trigger: ";paragraph", replace: "¶"}
  - {trigger: ";pilcrow",   replace: "¶"}
  - {trigger: ";emdash",    replace: "—"}
  - {trigger: ";endash",    replace: "–"}
  - {trigger: ";lsquo",     replace: "‘"}
  - {trigger: ";rsquo",     replace: "’"}
  - {trigger: ";ldquo",     replace: "“"}
  - {trigger: ";rdquo",     replace: "”"}
  - {trigger: ";...",       replace: "…"}
