# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple Expansions
  - {trigger: ";cdck", replace: "Civilized Discourse Construction Kit"}
  - {trigger: ";kem", replace: "Kyle E. Mitchell"}
  - {trigger: ";email", replace: "kyle@kemitchell.com"}

  # Dates
  - trigger: ";today"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: shell
        params:
          cmd: ~/.local/bin/today

  - trigger: ";tomorrow"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: shell
        params:
          cmd: ~/.local/bin/tomorrow

  - trigger: ";monday"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: shell
        params:
          cmd: ~/.local/bin/nextmonday

  - trigger: ";friday"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: shell
        params:
          cmd: ~/.local/bin/friday

  # Symbols
  - {trigger: ";section", replace: "§"}
  - {trigger: ";paragraph", replace: "¶"}
  - {trigger: ";pilcrow", replace: "¶"}
  - {trigger: ";emdash", replace: "—"}
  - {trigger: ";endash", replace: "–"}
  - {trigger: ";lsquo", replace: "‘"}
  - {trigger: ";rsquo", replace: "’"}
  - {trigger: ";ldquo", replace: "“"}
  - {trigger: ";rdquo", replace: "”"}
  - {trigger: ";...", replace: "…"}
